
package com.haier.hevwms.sto.service.vnpt;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublishServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublishServiceSoap {


    /**
     * 
     * @param username
     * @param xmlInvData
     * @param pattern
     * @param aCpass
     * @param convert
     * @param account
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ImportAndPublishInv", action = "http://tempuri.org/ImportAndPublishInv")
    @WebResult(name = "ImportAndPublishInvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ImportAndPublishInv", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportAndPublishInv")
    @ResponseWrapper(localName = "ImportAndPublishInvResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportAndPublishInvResponse")
    public String importAndPublishInv(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial,
        @WebParam(name = "convert", targetNamespace = "http://tempuri.org/")
        int convert);

    /**
     * 
     * @param username
     * @param xmlInvData
     * @param pattern
     * @param aCpass
     * @param convert
     * @param account
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ImportAndPublishAssignedNo", action = "http://tempuri.org/ImportAndPublishAssignedNo")
    @WebResult(name = "ImportAndPublishAssignedNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ImportAndPublishAssignedNo", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportAndPublishAssignedNo")
    @ResponseWrapper(localName = "ImportAndPublishAssignedNoResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportAndPublishAssignedNoResponse")
    public String importAndPublishAssignedNo(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial,
        @WebParam(name = "convert", targetNamespace = "http://tempuri.org/")
        int convert);

    /**
     * 
     * @param username
     * @param xmlInvData
     * @param convert
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ImportInv", action = "http://tempuri.org/ImportInv")
    @WebResult(name = "ImportInvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ImportInv", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportInv")
    @ResponseWrapper(localName = "ImportInvResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportInvResponse")
    public String importInv(
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "convert", targetNamespace = "http://tempuri.org/")
        int convert);

    /**
     * 
     * @param username
     * @param xmlInvData
     * @param pattern
     * @param aCpass
     * @param convert
     * @param account
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ImportInvByPattern", action = "http://tempuri.org/ImportInvByPattern")
    @WebResult(name = "ImportInvByPatternResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ImportInvByPattern", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportInvByPattern")
    @ResponseWrapper(localName = "ImportInvByPatternResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportInvByPatternResponse")
    public String importInvByPattern(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial,
        @WebParam(name = "convert", targetNamespace = "http://tempuri.org/")
        int convert);

    /**
     * 
     * @param username
     * @param aCpass
     * @param account
     * @param lstFkey
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/deleteInvoiceByFkey")
    @WebResult(name = "deleteInvoiceByFkeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "deleteInvoiceByFkey", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.DeleteInvoiceByFkey")
    @ResponseWrapper(localName = "deleteInvoiceByFkeyResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.DeleteInvoiceByFkeyResponse")
    public String deleteInvoiceByFkey(
        @WebParam(name = "lstFkey", targetNamespace = "http://tempuri.org/")
        String lstFkey,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass);

    /**
     * 
     * @param pattern
     * @param fkey
     * @param account
     * @param userName
     * @param accPass
     * @param userPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInvDataByFkey", action = "http://tempuri.org/GetInvDataByFkey")
    @WebResult(name = "GetInvDataByFkeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInvDataByFkey", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetInvDataByFkey")
    @ResponseWrapper(localName = "GetInvDataByFkeyResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetInvDataByFkeyResponse")
    public String getInvDataByFkey(
        @WebParam(name = "fkey", targetNamespace = "http://tempuri.org/")
        String fkey,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "userPass", targetNamespace = "http://tempuri.org/")
        String userPass,
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "accPass", targetNamespace = "http://tempuri.org/")
        String accPass,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern);

    /**
     * 
     * @param lstID
     * @param username
     * @param aCpass
     * @param account
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/deleteInvoiceByID")
    @WebResult(name = "deleteInvoiceByIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "deleteInvoiceByID", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.DeleteInvoiceByID")
    @ResponseWrapper(localName = "deleteInvoiceByIDResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.DeleteInvoiceByIDResponse")
    public String deleteInvoiceByID(
        @WebParam(name = "lstID", targetNamespace = "http://tempuri.org/")
        String lstID,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass);

    /**
     * 
     * @param username
     * @param pattern
     * @param invIDs
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/publishInv")
    @WebResult(name = "publishInvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "publishInv", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.PublishInv")
    @ResponseWrapper(localName = "publishInvResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.PublishInvResponse")
    public String publishInv(
        @WebParam(name = "invIDs", targetNamespace = "http://tempuri.org/")
        ArrayOfInt invIDs,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial);

    /**
     * 
     * @param username
     * @param pattern
     * @param lsFkey
     * @param aCpass
     * @param account
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PublishInvFkey", action = "http://tempuri.org/PublishInvFkey")
    @WebResult(name = "PublishInvFkeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PublishInvFkey", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.PublishInvFkey")
    @ResponseWrapper(localName = "PublishInvFkeyResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.PublishInvFkeyResponse")
    public String publishInvFkey(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "lsFkey", targetNamespace = "http://tempuri.org/")
        String lsFkey,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial);

    /**
     * 
     * @param username
     * @param fromDate
     * @param aCpass
     * @param account
     * @param toDate
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PublishInvByDate", action = "http://tempuri.org/PublishInvByDate")
    @WebResult(name = "PublishInvByDateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PublishInvByDate", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.PublishInvByDate")
    @ResponseWrapper(localName = "PublishInvByDateResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.PublishInvByDateResponse")
    public String publishInvByDate(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "FromDate", targetNamespace = "http://tempuri.org/")
        String fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://tempuri.org/")
        String toDate);

    /**
     * 
     * @param username
     * @param xmlCusData
     * @param convert
     * @param pass
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UpdateCus", action = "http://tempuri.org/UpdateCus")
    @WebResult(name = "UpdateCusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateCus", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.UpdateCus")
    @ResponseWrapper(localName = "UpdateCusResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.UpdateCusResponse")
    public int updateCus(
        @WebParam(name = "XMLCusData", targetNamespace = "http://tempuri.org/")
        String xmlCusData,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "convert", targetNamespace = "http://tempuri.org/")
        Integer convert);

    /**
     * 
     * @param username
     * @param cusCode
     * @param certSerial
     * @param pass
     * @param certString
     * @return
     *     returns int
     */
    @WebMethod(action = "http://tempuri.org/setCusCert")
    @WebResult(name = "setCusCertResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "setCusCert", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SetCusCert")
    @ResponseWrapper(localName = "setCusCertResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SetCusCertResponse")
    public int setCusCert(
        @WebParam(name = "certSerial", targetNamespace = "http://tempuri.org/")
        String certSerial,
        @WebParam(name = "certString", targetNamespace = "http://tempuri.org/")
        String certString,
        @WebParam(name = "cusCode", targetNamespace = "http://tempuri.org/")
        String cusCode,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass);

    /**
     * 
     * @param productXml
     * @param userName
     * @param account
     * @param password
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ImportFromXml", action = "http://tempuri.org/ImportFromXml")
    @WebResult(name = "ImportFromXmlResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ImportFromXml", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportFromXml")
    @ResponseWrapper(localName = "ImportFromXmlResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportFromXmlResponse")
    public String importFromXml(
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "productXml", targetNamespace = "http://tempuri.org/")
        String productXml);

    /**
     * 
     * @param userName
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCertInfo", action = "http://tempuri.org/GetCertInfo")
    @WebResult(name = "GetCertInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCertInfo", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetCertInfo")
    @ResponseWrapper(localName = "GetCertInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetCertInfoResponse")
    public String getCertInfo(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param aCpass
     * @param account
     * @param req
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/syncInfomation")
    @WebResult(name = "syncInfomationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "syncInfomation", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncInfomation")
    @ResponseWrapper(localName = "syncInfomationResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncInfomationResponse")
    public String syncInfomation(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        String req);

    /**
     * 
     * @param userName
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SignIn", action = "http://tempuri.org/SignIn")
    @WebResult(name = "SignInResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SignIn", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SignIn")
    @ResponseWrapper(localName = "SignInResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SignInResponse")
    public String signIn(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass);

    /**
     * 
     * @param account
     * @param oldPass
     * @param newPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/resetPassword")
    @WebResult(name = "resetPasswordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "resetPassword", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ResetPassword")
    @ResponseWrapper(localName = "resetPasswordResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ResetPasswordResponse")
    public String resetPassword(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "oldPass", targetNamespace = "http://tempuri.org/")
        String oldPass,
        @WebParam(name = "newPass", targetNamespace = "http://tempuri.org/")
        String newPass);

    /**
     * 
     * @param aCpass
     * @param account
     * @param req
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AppClientSyncInfoSystem", action = "http://tempuri.org/AppClientSyncInfoSystem")
    @WebResult(name = "AppClientSyncInfoSystemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AppClientSyncInfoSystem", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.AppClientSyncInfoSystem")
    @ResponseWrapper(localName = "AppClientSyncInfoSystemResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.AppClientSyncInfoSystemResponse")
    public String appClientSyncInfoSystem(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        String req);

    /**
     * 
     * @param pattern
     * @param account
     * @param serial
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getCurrentNo")
    @WebResult(name = "getCurrentNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getCurrentNo", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetCurrentNo")
    @ResponseWrapper(localName = "getCurrentNoResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetCurrentNoResponse")
    public String getCurrentNo(
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial);

    /**
     * 
     * @param xmlInvData
     * @param username
     * @param convert
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/syncClientInv")
    @WebResult(name = "syncClientInvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "syncClientInv", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncClientInv")
    @ResponseWrapper(localName = "syncClientInvResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncClientInvResponse")
    public String syncClientInv(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData,
        @WebParam(name = "convert", targetNamespace = "http://tempuri.org/")
        int convert);

    /**
     * 
     * @param xmlInvData
     * @param username
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updateInvoice")
    @WebResult(name = "updateInvoiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateInvoice", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.UpdateInvoice")
    @ResponseWrapper(localName = "updateInvoiceResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.UpdateInvoiceResponse")
    public String updateInvoice(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData);

    /**
     * 
     * @param xmlDecision
     * @param account
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/syncDecision")
    @WebResult(name = "syncDecisionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "syncDecision", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncDecision")
    @ResponseWrapper(localName = "syncDecisionResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncDecisionResponse")
    public String syncDecision(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "xmlDecision", targetNamespace = "http://tempuri.org/")
        String xmlDecision);

    /**
     * 
     * @param account
     * @param xmlPublish
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/syncPublish")
    @WebResult(name = "syncPublishResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "syncPublish", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncPublish")
    @ResponseWrapper(localName = "syncPublishResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncPublishResponse")
    public String syncPublish(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "xmlPublish", targetNamespace = "http://tempuri.org/")
        String xmlPublish);

    /**
     * 
     * @param account
     * @param comtaxCode
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPublishInv", action = "http://tempuri.org/GetPublishInv")
    @WebResult(name = "GetPublishInvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPublishInv", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetPublishInv")
    @ResponseWrapper(localName = "GetPublishInvResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetPublishInvResponse")
    public String getPublishInv(
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "comtaxCode", targetNamespace = "http://tempuri.org/")
        String comtaxCode);

    /**
     * 
     * @param xmlInvCancel
     * @param account
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/syncInvCancel")
    @WebResult(name = "syncInvCancelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "syncInvCancel", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncInvCancel")
    @ResponseWrapper(localName = "syncInvCancelResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncInvCancelResponse")
    public String syncInvCancel(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "xmlInvCancel", targetNamespace = "http://tempuri.org/")
        String xmlInvCancel);

    /**
     * 
     * @param account
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getDateTimeServer")
    @WebResult(name = "getDateTimeServerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getDateTimeServer", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetDateTimeServer")
    @ResponseWrapper(localName = "getDateTimeServerResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetDateTimeServerResponse")
    public String getDateTimeServer(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Pass", targetNamespace = "http://tempuri.org/")
        String pass);

    /**
     * 
     * @param xmlInvoiceCancel
     * @param account
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/syncClientInvoiceCancel")
    @WebResult(name = "syncClientInvoiceCancelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "syncClientInvoiceCancel", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncClientInvoiceCancel")
    @ResponseWrapper(localName = "syncClientInvoiceCancelResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncClientInvoiceCancelResponse")
    public String syncClientInvoiceCancel(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "xmlInvoiceCancel", targetNamespace = "http://tempuri.org/")
        String xmlInvoiceCancel);

    /**
     * 
     * @param id
     * @param account
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConvertForVerify", action = "http://tempuri.org/ConvertForVerify")
    @WebResult(name = "ConvertForVerifyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConvertForVerify", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ConvertForVerify")
    @ResponseWrapper(localName = "ConvertForVerifyResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ConvertForVerifyResponse")
    public String convertForVerify(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "Id", targetNamespace = "http://tempuri.org/")
        int id);

    /**
     * 
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/sendEmail")
    @WebResult(name = "sendEmailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendEmailResponse")
    public String sendEmail(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username);

    /**
     * 
     * @param account
     * @param xmlCert
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/syncCert")
    @WebResult(name = "syncCertResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "syncCert", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncCert")
    @ResponseWrapper(localName = "syncCertResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncCertResponse")
    public String syncCert(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "xmlCert", targetNamespace = "http://tempuri.org/")
        String xmlCert);

    /**
     * 
     * @param username
     * @param currentYear
     * @param lastSync
     * @param comtaxCode
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/syncInvoicev2")
    @WebResult(name = "syncInvoicev2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "syncInvoicev2", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncInvoicev2")
    @ResponseWrapper(localName = "syncInvoicev2Response", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncInvoicev2Response")
    public String syncInvoicev2(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "comtaxCode", targetNamespace = "http://tempuri.org/")
        String comtaxCode,
        @WebParam(name = "currentYear", targetNamespace = "http://tempuri.org/")
        String currentYear,
        @WebParam(name = "lastSync", targetNamespace = "http://tempuri.org/")
        String lastSync);

    /**
     * 
     * @param username
     * @param lastSync
     * @param comtaxCode
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/syncInvoice")
    @WebResult(name = "syncInvoiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "syncInvoice", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncInvoice")
    @ResponseWrapper(localName = "syncInvoiceResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SyncInvoiceResponse")
    public String syncInvoice(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "comtaxCode", targetNamespace = "http://tempuri.org/")
        String comtaxCode,
        @WebParam(name = "lastSync", targetNamespace = "http://tempuri.org/")
        String lastSync);

    /**
     * 
     * @param username
     * @param pattern
     * @param comtaxcode
     * @param isReSync
     * @param serial
     * @param password
     * @param notax
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSingleInvoice", action = "http://tempuri.org/GetSingleInvoice")
    @WebResult(name = "GetSingleInvoiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSingleInvoice", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetSingleInvoice")
    @ResponseWrapper(localName = "GetSingleInvoiceResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetSingleInvoiceResponse")
    public String getSingleInvoice(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "comtaxcode", targetNamespace = "http://tempuri.org/")
        String comtaxcode,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial,
        @WebParam(name = "notax", targetNamespace = "http://tempuri.org/")
        String notax,
        @WebParam(name = "isReSync", targetNamespace = "http://tempuri.org/")
        int isReSync);

    /**
     * 
     * @param id
     * @param payment
     * @param account
     * @param note
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PaymentForVerify", action = "http://tempuri.org/PaymentForVerify")
    @WebResult(name = "PaymentForVerifyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PaymentForVerify", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.PaymentForVerify")
    @ResponseWrapper(localName = "PaymentForVerifyResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.PaymentForVerifyResponse")
    public String paymentForVerify(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "Id", targetNamespace = "http://tempuri.org/")
        int id,
        @WebParam(name = "payment", targetNamespace = "http://tempuri.org/")
        int payment,
        @WebParam(name = "note", targetNamespace = "http://tempuri.org/")
        String note);

    /**
     * 
     * @param xmlInvData
     * @param username
     * @param pattern
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/sendEmailAgain")
    @WebResult(name = "sendEmailAgainResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sendEmailAgain", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendEmailAgain")
    @ResponseWrapper(localName = "sendEmailAgainResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendEmailAgainResponse")
    public String sendEmailAgain(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData);

    /**
     * 
     * @param serialCert
     * @param username
     * @param xmlInvData
     * @param pattern
     * @param aCpass
     * @param convert
     * @param invToken
     * @param account
     * @param type
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getHashInvWithToken")
    @WebResult(name = "getHashInvWithTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getHashInvWithToken", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetHashInvWithToken")
    @ResponseWrapper(localName = "getHashInvWithTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetHashInvWithTokenResponse")
    public String getHashInvWithToken(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "serialCert", targetNamespace = "http://tempuri.org/")
        String serialCert,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        int type,
        @WebParam(name = "invToken", targetNamespace = "http://tempuri.org/")
        String invToken,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial,
        @WebParam(name = "convert", targetNamespace = "http://tempuri.org/")
        int convert);

    /**
     * 
     * @param username
     * @param xmlInvData
     * @param pattern
     * @param aCpass
     * @param account
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/publishInvWithToken")
    @WebResult(name = "publishInvWithTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "publishInvWithToken", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.PublishInvWithToken")
    @ResponseWrapper(localName = "publishInvWithTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.PublishInvWithTokenResponse")
    public String publishInvWithToken(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial);

    /**
     * 
     * @param username
     * @param xmlInvData
     * @param pattern
     * @param aCpass
     * @param account
     * @param type
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AdjustReplaceInvWithToken", action = "http://tempuri.org/AdjustReplaceInvWithToken")
    @WebResult(name = "AdjustReplaceInvWithTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AdjustReplaceInvWithToken", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.AdjustReplaceInvWithToken")
    @ResponseWrapper(localName = "AdjustReplaceInvWithTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.AdjustReplaceInvWithTokenResponse")
    public String adjustReplaceInvWithToken(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        int type,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial);

    /**
     * 
     * @param username
     * @param pattern
     * @param xmlData
     * @param aCpass
     * @param account
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelInvoiceWithToken", action = "http://tempuri.org/CancelInvoiceWithToken")
    @WebResult(name = "CancelInvoiceWithTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelInvoiceWithToken", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.CancelInvoiceWithToken")
    @ResponseWrapper(localName = "CancelInvoiceWithTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.CancelInvoiceWithTokenResponse")
    public String cancelInvoiceWithToken(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xmlData", targetNamespace = "http://tempuri.org/")
        String xmlData,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern);

    /**
     * 
     * @param id
     * @param username
     * @param pattern
     * @param aCpass
     * @param account
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/rolBackWithToken")
    @WebResult(name = "rolBackWithTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "rolBackWithToken", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.RolBackWithToken")
    @ResponseWrapper(localName = "rolBackWithTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.RolBackWithTokenResponse")
    public String rolBackWithToken(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern);

    /**
     * 
     * @param username
     * @param aCpass
     * @param account
     * @param password
     * @param certStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/importCertWithToken")
    @WebResult(name = "importCertWithTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "importCertWithToken", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportCertWithToken")
    @ResponseWrapper(localName = "importCertWithTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportCertWithTokenResponse")
    public String importCertWithToken(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "certStr", targetNamespace = "http://tempuri.org/")
        String certStr);

    /**
     * 
     * @param username
     * @param pattern
     * @param aCpass
     * @param account
     * @param xmlFkeyInv
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getStatusInv")
    @WebResult(name = "getStatusInvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getStatusInv", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetStatusInv")
    @ResponseWrapper(localName = "getStatusInvResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetStatusInvResponse")
    public String getStatusInv(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "xmlFkeyInv", targetNamespace = "http://tempuri.org/")
        String xmlFkeyInv,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern);

    /**
     * 
     * @param serialCert
     * @param username
     * @param pattern
     * @param aCpass
     * @param account
     * @param xmlFkeyInv
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getHashInv")
    @WebResult(name = "getHashInvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getHashInv", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetHashInv")
    @ResponseWrapper(localName = "getHashInvResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetHashInvResponse")
    public String getHashInv(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "serialCert", targetNamespace = "http://tempuri.org/")
        String serialCert,
        @WebParam(name = "xmlFkeyInv", targetNamespace = "http://tempuri.org/")
        String xmlFkeyInv,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern);

    /**
     * 
     * @param username
     * @param pattern
     * @param comtaxcode
     * @param fkey
     * @param serial
     * @param password
     * @param notax
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInvoiceByFkey", action = "http://tempuri.org/GetInvoiceByFkey")
    @WebResult(name = "GetInvoiceByFkeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInvoiceByFkey", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetInvoiceByFkey")
    @ResponseWrapper(localName = "GetInvoiceByFkeyResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetInvoiceByFkeyResponse")
    public String getInvoiceByFkey(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "comtaxcode", targetNamespace = "http://tempuri.org/")
        String comtaxcode,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial,
        @WebParam(name = "notax", targetNamespace = "http://tempuri.org/")
        String notax,
        @WebParam(name = "fkey", targetNamespace = "http://tempuri.org/")
        String fkey);

    /**
     * 
     * @param username
     * @param comtaxcode
     * @param password
     * @param fkeys
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInvoiceByFkeys", action = "http://tempuri.org/GetInvoiceByFkeys")
    @WebResult(name = "GetInvoiceByFkeysResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInvoiceByFkeys", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetInvoiceByFkeys")
    @ResponseWrapper(localName = "GetInvoiceByFkeysResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetInvoiceByFkeysResponse")
    public String getInvoiceByFkeys(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "comtaxcode", targetNamespace = "http://tempuri.org/")
        String comtaxcode,
        @WebParam(name = "fkeys", targetNamespace = "http://tempuri.org/")
        ArrayOfString fkeys);

    /**
     * 
     * @param usernameService
     * @param pattern
     * @param passwordService
     * @param dateTo
     * @param dateFrom
     * @param serial
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInForPublishCom", action = "http://tempuri.org/GetInForPublishCom")
    @WebResult(name = "GetInForPublishComResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInForPublishCom", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetInForPublishCom")
    @ResponseWrapper(localName = "GetInForPublishComResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetInForPublishComResponse")
    public String getInForPublishCom(
        @WebParam(name = "usernameService", targetNamespace = "http://tempuri.org/")
        String usernameService,
        @WebParam(name = "passwordService", targetNamespace = "http://tempuri.org/")
        String passwordService,
        @WebParam(name = "Pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "Serial", targetNamespace = "http://tempuri.org/")
        String serial,
        @WebParam(name = "DateFrom", targetNamespace = "http://tempuri.org/")
        String dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://tempuri.org/")
        String dateTo);

    /**
     * 
     * @param username
     * @param xmlDataInvoiceEmail
     * @param aCpass
     * @param account
     * @param hdPattern
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendAgainEmailServ", action = "http://tempuri.org/SendAgainEmailServ")
    @WebResult(name = "SendAgainEmailServResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendAgainEmailServ", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendAgainEmailServ")
    @ResponseWrapper(localName = "SendAgainEmailServResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendAgainEmailServResponse")
    public String sendAgainEmailServ(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "xmlDataInvoiceEmail", targetNamespace = "http://tempuri.org/")
        String xmlDataInvoiceEmail,
        @WebParam(name = "hdPattern", targetNamespace = "http://tempuri.org/")
        String hdPattern,
        @WebParam(name = "Serial", targetNamespace = "http://tempuri.org/")
        String serial);

    /**
     * 
     * @param pattern
     * @param arisingDate
     * @param no
     * @param aCpass
     * @param noNew
     * @param account
     * @param noO
     * @param serialO
     * @param type
     * @param serial
     * @param key
     * @param publishDate
     * @param isUpdate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDataInvHsm", action = "http://tempuri.org/GetDataInvHsm")
    @WebResult(name = "GetDataInvHsmResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDataInvHsm", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetDataInvHsm")
    @ResponseWrapper(localName = "GetDataInvHsmResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetDataInvHsmResponse")
    public String getDataInvHsm(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial,
        @WebParam(name = "no", targetNamespace = "http://tempuri.org/")
        BigDecimal no,
        @WebParam(name = "noNew", targetNamespace = "http://tempuri.org/")
        BigDecimal noNew,
        @WebParam(name = "publishDate", targetNamespace = "http://tempuri.org/")
        String publishDate,
        @WebParam(name = "arisingDate", targetNamespace = "http://tempuri.org/")
        String arisingDate,
        @WebParam(name = "serialO", targetNamespace = "http://tempuri.org/")
        String serialO,
        @WebParam(name = "noO", targetNamespace = "http://tempuri.org/")
        int noO,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        int type,
        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        String key,
        @WebParam(name = "isUpdate", targetNamespace = "http://tempuri.org/")
        int isUpdate);

    /**
     * 
     * @param username
     * @param xmlInvData
     * @param pattern
     * @param aCpass
     * @param convert
     * @param invToken
     * @param account
     * @param type
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ImportAndPublishInvSignService", action = "http://tempuri.org/ImportAndPublishInvSignService")
    @WebResult(name = "ImportAndPublishInvSignServiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ImportAndPublishInvSignService", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportAndPublishInvSignService")
    @ResponseWrapper(localName = "ImportAndPublishInvSignServiceResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ImportAndPublishInvSignServiceResponse")
    public String importAndPublishInvSignService(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        int type,
        @WebParam(name = "invToken", targetNamespace = "http://tempuri.org/")
        String invToken,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial,
        @WebParam(name = "convert", targetNamespace = "http://tempuri.org/")
        int convert);

    /**
     * 
     * @param username
     * @param invTokens
     * @param aCpass
     * @param account
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMCCQThueByInvTokens", action = "http://tempuri.org/GetMCCQThueByInvTokens")
    @WebResult(name = "GetMCCQThueByInvTokensResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMCCQThueByInvTokens", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetMCCQThueByInvTokens")
    @ResponseWrapper(localName = "GetMCCQThueByInvTokensResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetMCCQThueByInvTokensResponse")
    public String getMCCQThueByInvTokens(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "invTokens", targetNamespace = "http://tempuri.org/")
        String invTokens);

    /**
     * 
     * @param username
     * @param pattern
     * @param aCpass
     * @param account
     * @param password
     * @param fkeys
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMCCQThueByFkeys", action = "http://tempuri.org/GetMCCQThueByFkeys")
    @WebResult(name = "GetMCCQThueByFkeysResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMCCQThueByFkeys", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetMCCQThueByFkeys")
    @ResponseWrapper(localName = "GetMCCQThueByFkeysResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetMCCQThueByFkeysResponse")
    public String getMCCQThueByFkeys(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "fkeys", targetNamespace = "http://tempuri.org/")
        String fkeys);

    /**
     * 
     * @param username
     * @param invTokens
     * @param aCpass
     * @param account
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMCCQThueByInvTokensNoXMLSign", action = "http://tempuri.org/GetMCCQThueByInvTokensNoXMLSign")
    @WebResult(name = "GetMCCQThueByInvTokensNoXMLSignResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMCCQThueByInvTokensNoXMLSign", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetMCCQThueByInvTokensNoXMLSign")
    @ResponseWrapper(localName = "GetMCCQThueByInvTokensNoXMLSignResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetMCCQThueByInvTokensNoXMLSignResponse")
    public String getMCCQThueByInvTokensNoXMLSign(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "invTokens", targetNamespace = "http://tempuri.org/")
        String invTokens);

    /**
     * 
     * @param username
     * @param pattern
     * @param aCpass
     * @param account
     * @param password
     * @param fkeys
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMCCQThueByFkeysNoXMLSign", action = "http://tempuri.org/GetMCCQThueByFkeysNoXMLSign")
    @WebResult(name = "GetMCCQThueByFkeysNoXMLSignResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMCCQThueByFkeysNoXMLSign", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetMCCQThueByFkeysNoXMLSign")
    @ResponseWrapper(localName = "GetMCCQThueByFkeysNoXMLSignResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetMCCQThueByFkeysNoXMLSignResponse")
    public String getMCCQThueByFkeysNoXMLSign(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "fkeys", targetNamespace = "http://tempuri.org/")
        String fkeys);

    /**
     * 
     * @param username
     * @param pattern
     * @param aCpass
     * @param account
     * @param password
     * @param fkeys
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendInvToCQTByFkeys", action = "http://tempuri.org/SendInvToCQTByFkeys")
    @WebResult(name = "SendInvToCQTByFkeysResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendInvToCQTByFkeys", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendInvToCQTByFkeys")
    @ResponseWrapper(localName = "SendInvToCQTByFkeysResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendInvToCQTByFkeysResponse")
    public String sendInvToCQTByFkeys(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "fkeys", targetNamespace = "http://tempuri.org/")
        String fkeys);

    /**
     * 
     * @param username
     * @param invTokens
     * @param aCpass
     * @param account
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendInvToCQTByInvTokens", action = "http://tempuri.org/SendInvToCQTByInvTokens")
    @WebResult(name = "SendInvToCQTByInvTokensResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendInvToCQTByInvTokens", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendInvToCQTByInvTokens")
    @ResponseWrapper(localName = "SendInvToCQTByInvTokensResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendInvToCQTByInvTokensResponse")
    public String sendInvToCQTByInvTokens(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "invTokens", targetNamespace = "http://tempuri.org/")
        String invTokens);

    /**
     * 
     * @param username
     * @param pattern
     * @param aCpass
     * @param convert
     * @param account
     * @param xml
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendInvNoticeErrors", action = "http://tempuri.org/SendInvNoticeErrors")
    @WebResult(name = "SendInvNoticeErrorsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendInvNoticeErrors", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendInvNoticeErrors")
    @ResponseWrapper(localName = "SendInvNoticeErrorsResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendInvNoticeErrorsResponse")
    public String sendInvNoticeErrors(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
        String xml,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "convert", targetNamespace = "http://tempuri.org/")
        int convert);

    /**
     * 
     * @param username
     * @param pattern
     * @param aCpass
     * @param convert
     * @param account
     * @param xml
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetHashInvNoticeErrors", action = "http://tempuri.org/GetHashInvNoticeErrors")
    @WebResult(name = "GetHashInvNoticeErrorsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetHashInvNoticeErrors", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetHashInvNoticeErrors")
    @ResponseWrapper(localName = "GetHashInvNoticeErrorsResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetHashInvNoticeErrorsResponse")
    public String getHashInvNoticeErrors(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
        String xml,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "convert", targetNamespace = "http://tempuri.org/")
        int convert);

    /**
     * 
     * @param username
     * @param pattern
     * @param aCpass
     * @param convert
     * @param account
     * @param xml
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetHashInvNoticeErrorsWithSmartCA", action = "http://tempuri.org/GetHashInvNoticeErrorsWithSmartCA")
    @WebResult(name = "GetHashInvNoticeErrorsWithSmartCAResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetHashInvNoticeErrorsWithSmartCA", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetHashInvNoticeErrorsWithSmartCA")
    @ResponseWrapper(localName = "GetHashInvNoticeErrorsWithSmartCAResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetHashInvNoticeErrorsWithSmartCAResponse")
    public String getHashInvNoticeErrorsWithSmartCA(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
        String xml,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "convert", targetNamespace = "http://tempuri.org/")
        int convert);

    /**
     * 
     * @param username
     * @param aCpass
     * @param account
     * @param xml
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendInvNoticeErrorsWithSmartCA", action = "http://tempuri.org/SendInvNoticeErrorsWithSmartCA")
    @WebResult(name = "SendInvNoticeErrorsWithSmartCAResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendInvNoticeErrorsWithSmartCA", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendInvNoticeErrorsWithSmartCA")
    @ResponseWrapper(localName = "SendInvNoticeErrorsWithSmartCAResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendInvNoticeErrorsWithSmartCAResponse")
    public String sendInvNoticeErrorsWithSmartCA(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
        String xml);

    /**
     * 
     * @param username
     * @param aCpass
     * @param account
     * @param xml
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendInvNoticeErrorsWidthToken", action = "http://tempuri.org/SendInvNoticeErrorsWidthToken")
    @WebResult(name = "SendInvNoticeErrorsWidthTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendInvNoticeErrorsWidthToken", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendInvNoticeErrorsWidthToken")
    @ResponseWrapper(localName = "SendInvNoticeErrorsWidthTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.SendInvNoticeErrorsWidthTokenResponse")
    public String sendInvNoticeErrorsWidthToken(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
        String xml);

    /**
     * 
     * @param mtd
     * @param username
     * @param aCpass
     * @param account
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HandleInvoiceErrors", action = "http://tempuri.org/HandleInvoiceErrors")
    @WebResult(name = "HandleInvoiceErrorsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HandleInvoiceErrors", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.HandleInvoiceErrors")
    @ResponseWrapper(localName = "HandleInvoiceErrorsResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.HandleInvoiceErrorsResponse")
    public String handleInvoiceErrors(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "mtd", targetNamespace = "http://tempuri.org/")
        String mtd);

    /**
     * 
     * @param mtd
     * @param username
     * @param aCpass
     * @param account
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReceivedInvoiceErrors", action = "http://tempuri.org/ReceivedInvoiceErrors")
    @WebResult(name = "ReceivedInvoiceErrorsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReceivedInvoiceErrors", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ReceivedInvoiceErrors")
    @ResponseWrapper(localName = "ReceivedInvoiceErrorsResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ReceivedInvoiceErrorsResponse")
    public String receivedInvoiceErrors(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "mtd", targetNamespace = "http://tempuri.org/")
        String mtd);

    /**
     * 
     * @param serialCert
     * @param username
     * @param xmlInvData
     * @param pattern
     * @param aCpass
     * @param convert
     * @param invToken
     * @param account
     * @param type
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetHashInvSmartCA", action = "http://tempuri.org/GetHashInvSmartCA")
    @WebResult(name = "GetHashInvSmartCAResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetHashInvSmartCA", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetHashInvSmartCA")
    @ResponseWrapper(localName = "GetHashInvSmartCAResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetHashInvSmartCAResponse")
    public String getHashInvSmartCA(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "serialCert", targetNamespace = "http://tempuri.org/")
        String serialCert,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        int type,
        @WebParam(name = "invToken", targetNamespace = "http://tempuri.org/")
        String invToken,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial,
        @WebParam(name = "convert", targetNamespace = "http://tempuri.org/")
        int convert);

    /**
     * 
     * @param username
     * @param xmlInvData
     * @param pattern
     * @param aCpass
     * @param account
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PublishInvSmartCA", action = "http://tempuri.org/PublishInvSmartCA")
    @WebResult(name = "PublishInvSmartCAResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PublishInvSmartCA", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.PublishInvSmartCA")
    @ResponseWrapper(localName = "PublishInvSmartCAResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.PublishInvSmartCAResponse")
    public String publishInvSmartCA(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial);

    /**
     * 
     * @param id
     * @param serialCert
     * @param certType
     * @param aCpass
     * @param account
     * @param certinfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateCertificate", action = "http://tempuri.org/UpdateCertificate")
    @WebResult(name = "UpdateCertificateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateCertificate", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.UpdateCertificate")
    @ResponseWrapper(localName = "UpdateCertificateResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.UpdateCertificateResponse")
    public String updateCertificate(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "certinfo", targetNamespace = "http://tempuri.org/")
        String certinfo,
        @WebParam(name = "serialCert", targetNamespace = "http://tempuri.org/")
        String serialCert,
        @WebParam(name = "certType", targetNamespace = "http://tempuri.org/")
        int certType,
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id);

    /**
     * 
     * @param id
     * @param aCpass
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteCertificate", action = "http://tempuri.org/DeleteCertificate")
    @WebResult(name = "DeleteCertificateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteCertificate", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.DeleteCertificate")
    @ResponseWrapper(localName = "DeleteCertificateResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.DeleteCertificateResponse")
    public String deleteCertificate(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id);

    /**
     * 
     * @param userName
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCertificates", action = "http://tempuri.org/GetCertificates")
    @WebResult(name = "GetCertificatesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCertificates", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetCertificates")
    @ResponseWrapper(localName = "GetCertificatesResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetCertificatesResponse")
    public String getCertificates(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param username
     * @param xmlInvData
     * @param aCpass
     * @param account
     * @param type
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RegisterPublish", action = "http://tempuri.org/RegisterPublish")
    @WebResult(name = "RegisterPublishResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RegisterPublish", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.RegisterPublish")
    @ResponseWrapper(localName = "RegisterPublishResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.RegisterPublishResponse")
    public String registerPublish(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "xmlInvData", targetNamespace = "http://tempuri.org/")
        String xmlInvData,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        int type);

    /**
     * 
     * @param mtd
     * @param username
     * @param aCpass
     * @param account
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReceivedRegisterPublish", action = "http://tempuri.org/ReceivedRegisterPublish")
    @WebResult(name = "ReceivedRegisterPublishResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReceivedRegisterPublish", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ReceivedRegisterPublish")
    @ResponseWrapper(localName = "ReceivedRegisterPublishResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.ReceivedRegisterPublishResponse")
    public String receivedRegisterPublish(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "mtd", targetNamespace = "http://tempuri.org/")
        String mtd);

    /**
     * 
     * @param username
     * @param pattern
     * @param aCpass
     * @param account
     * @param quantity
     * @param type
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RegisterPublishInvoice", action = "http://tempuri.org/RegisterPublishInvoice")
    @WebResult(name = "RegisterPublishInvoiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RegisterPublishInvoice", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.RegisterPublishInvoice")
    @ResponseWrapper(localName = "RegisterPublishInvoiceResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.RegisterPublishInvoiceResponse")
    public String registerPublishInvoice(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "Pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "Type", targetNamespace = "http://tempuri.org/")
        String type,
        @WebParam(name = "Serial", targetNamespace = "http://tempuri.org/")
        String serial,
        @WebParam(name = "Quantity", targetNamespace = "http://tempuri.org/")
        int quantity);

    /**
     * 
     * @param username
     * @param pattern
     * @param aCpass
     * @param account
     * @param serial
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelPublishInvoice", action = "http://tempuri.org/CancelPublishInvoice")
    @WebResult(name = "CancelPublishInvoiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelPublishInvoice", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.CancelPublishInvoice")
    @ResponseWrapper(localName = "CancelPublishInvoiceResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.CancelPublishInvoiceResponse")
    public String cancelPublishInvoice(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "ACpass", targetNamespace = "http://tempuri.org/")
        String aCpass,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "Pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "Serial", targetNamespace = "http://tempuri.org/")
        String serial);

    /**
     * 
     * @param status
     * @param mtdiep
     * @param pageSize
     * @param toDate
     * @param password
     * @param pageIndex
     * @param message
     * @param invNo
     * @param username
     * @param fromDate
     * @param pattern
     * @param mltdiep
     * @param serial
     * @param step
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTransactionItems", action = "http://tempuri.org/GetTransactionItems")
    @WebResult(name = "GetTransactionItemsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTransactionItems", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetTransactionItems")
    @ResponseWrapper(localName = "GetTransactionItemsResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetTransactionItemsResponse")
    public String getTransactionItems(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "status", targetNamespace = "http://tempuri.org/")
        int status,
        @WebParam(name = "mtdiep", targetNamespace = "http://tempuri.org/")
        String mtdiep,
        @WebParam(name = "message", targetNamespace = "http://tempuri.org/")
        String message,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        String toDate,
        @WebParam(name = "mltdiep", targetNamespace = "http://tempuri.org/")
        String mltdiep,
        @WebParam(name = "pattern", targetNamespace = "http://tempuri.org/")
        String pattern,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial,
        @WebParam(name = "invNo", targetNamespace = "http://tempuri.org/")
        BigDecimal invNo,
        @WebParam(name = "step", targetNamespace = "http://tempuri.org/")
        int step,
        @WebParam(name = "pageIndex", targetNamespace = "http://tempuri.org/")
        int pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "http://tempuri.org/")
        int pageSize);

    /**
     * 
     * @param mtd
     * @param username
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTransactionDetail", action = "http://tempuri.org/GetTransactionDetail")
    @WebResult(name = "GetTransactionDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTransactionDetail", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetTransactionDetail")
    @ResponseWrapper(localName = "GetTransactionDetailResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetTransactionDetailResponse")
    public String getTransactionDetail(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "mtd", targetNamespace = "http://tempuri.org/")
        String mtd);

    /**
     * 
     * @param mtd
     * @param username
     * @param stepId
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetStepDetail", action = "http://tempuri.org/GetStepDetail")
    @WebResult(name = "GetStepDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStepDetail", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetStepDetail")
    @ResponseWrapper(localName = "GetStepDetailResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetStepDetailResponse")
    public String getStepDetail(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "stepId", targetNamespace = "http://tempuri.org/")
        String stepId,
        @WebParam(name = "mtd", targetNamespace = "http://tempuri.org/")
        String mtd);

    /**
     * 
     * @param id
     * @param username
     * @param password
     * @param tranErr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetResultsTransaction", action = "http://tempuri.org/GetResultsTransaction")
    @WebResult(name = "GetResultsTransactionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetResultsTransaction", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetResultsTransaction")
    @ResponseWrapper(localName = "GetResultsTransactionResponse", targetNamespace = "http://tempuri.org/", className = "com.haier.hevwms.sto.service.vnpt.GetResultsTransactionResponse")
    public String getResultsTransaction(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "Id", targetNamespace = "http://tempuri.org/")
        int id,
        @WebParam(name = "tranErr", targetNamespace = "http://tempuri.org/")
        boolean tranErr);

}
