
package com.haier.hevwms.sto.service.vnpt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublishService", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://aquavn-tt78admindemo.vnpt-invoice.com.vn/PublishService.asmx?wsdl")
public class PublishService
    extends Service
{

    private final static URL PUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLISHSERVICE_EXCEPTION;
    private final static QName PUBLISHSERVICE_QNAME = new QName("http://tempuri.org/", "PublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://aquavn-tt78admindemo.vnpt-invoice.com.vn/PublishService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLISHSERVICE_WSDL_LOCATION = url;
        PUBLISHSERVICE_EXCEPTION = e;
    }

    public PublishService() {
        super(__getWsdlLocation(), PUBLISHSERVICE_QNAME);
    }

    public PublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLISHSERVICE_QNAME, features);
    }

    public PublishService(URL wsdlLocation) {
        super(wsdlLocation, PUBLISHSERVICE_QNAME);
    }

    public PublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLISHSERVICE_QNAME, features);
    }

    public PublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublishServiceSoap
     */
    @WebEndpoint(name = "PublishServiceSoap")
    public PublishServiceSoap getPublishServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "PublishServiceSoap"), PublishServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublishServiceSoap
     */
    @WebEndpoint(name = "PublishServiceSoap")
    public PublishServiceSoap getPublishServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "PublishServiceSoap"), PublishServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PublishServiceSoap
     */
    @WebEndpoint(name = "PublishServiceSoap12")
    public PublishServiceSoap getPublishServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "PublishServiceSoap12"), PublishServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublishServiceSoap
     */
    @WebEndpoint(name = "PublishServiceSoap12")
    public PublishServiceSoap getPublishServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "PublishServiceSoap12"), PublishServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLISHSERVICE_EXCEPTION!= null) {
            throw PUBLISHSERVICE_EXCEPTION;
        }
        return PUBLISHSERVICE_WSDL_LOCATION;
    }

}
