SELECT
  ROW_ID
, DIVISION
, MATERIAL_NO
, CUSTOMER_MODEL
, MATERIAL_DESP
, BASIC_UNIT
, COLOR
, DATE_FORMAT(
		PLAN_DATE,
		'%Y-%m-%d %H:%i:%s'
	) PLAN_DATE
, PLAN_QTY
, STATUS
, FLAG
, CREATE_BY
, DATE_FORMAT(
		CREATE_DATE,
		'%Y-%m-%d %H:%i:%s'
	) CREATE_DATE
, MODIFY_BY
, DATE_FORMAT(
		MODIFY_DATE,
		'%Y-%m-%d %H:%i:%s'
	) MODIFY_DATE
, FAT_PLAN_DATE
, SERINO
, COUNTRY_CODE
FROM ods_opsi_info
WHERE
	MODIFY_DATE > DATE_ADD(NOW(), INTERVAL - 30 DAY)
AND COUNTRY_CODE = '6600'