SELECT
  ROW_ID
, PLAN_NO
, VEHICLE_TYPE
, QTY
, VEHICLE_PLAN_NO
, CONTRACT_NO
, CREATE_BY
, DATE_FORMAT(
		CREATE_DATE,
		'%Y-%m-%d %H:%i:%s'
	) CREATE_DATE
, MODIFY_BY
, DATE_FORMAT(
		MODIFY_DATE,
		'%Y-%m-%d %H:%i:%s'
	) MODIFY_DATE
, FLAG
, VERSION
, DATE_FORMAT(
		ARRIVE_DATE,
		'%Y-%m-%d %H:%i:%s'
	) ARRIVE_DATE
, COUNTRY_CODE
FROM ods_plan_cx_info
WHERE
	MODIFY_DATE > DATE_ADD(NOW(), INTERVAL - 30 DAY)
AND COUNTRY_CODE = '6600'