SELECT
  ROW_ID
, CX_PLAN_NO
, COST_DOC_NO
, PAYMENT_AMOUNT
, PAYMENT_TERM
, DATE_FORMAT(
		PAYMENT_DUE_DATE,
		'%Y-%m-%d %H:%i:%s'
	) PAYMENT_DUE_DATE
, CHECK_NO
, PAYMENT_STATUS
, CREATE_BY
, DATE_FORMAT(
		CREATE_DATE,
		'%Y-%m-%d %H:%i:%s'
	) CREATE_DATE
, MODIFY_BY
, DATE_FORMAT(
		MODIFY_DATE,
		'%Y-%m-%d %H:%i:%s'
	) MODIFY_DATE
, FLAG
, VERSION
, INDOOR_ID
, INVOICE_NUMBER
, APPLY_BY
, DATE_FORMAT(
		APPLY_DATE,
		'%Y-%m-%d %H:%i:%s'
	) APPLY_DATE
, COLLECTION_BY
, DATE_FORMAT(
		COLLECTION_DATE,
		'%Y-%m-%d %H:%i:%s'
	) COLLECTION_DATE
, TALLY_BY
, DATE_FORMAT(
		TALLY_DATE,
		'%Y-%m-%d %H:%i:%s'
	) TALLY_DATE
, DOC_TPYE
, ORDER_ID
, SAP_ORDER_NO
, SAP_ORDER_ITEM
, COMPANY_NAME
, MAT_SIZE
, TOTAL_SIZE
, SIZE_COST
, COUNTRY_CODE
FROM ods_logistic_cost
WHERE
	MODIFY_DATE > DATE_ADD(NOW(), INTERVAL - 30 DAY)
AND COUNTRY_CODE = '6600'