SELECT
	ROW_ID,
	WMS_ORDER_NO,
	WMS_ORDER_ITEM,
	ORDER_TYPE,
	DOC_TPYE,
	PLANT,
	WAREHOUSE_CODE,
	WAREHOUSE_NAME,
	LOCATION,
	MATERIAL_NO,
	CUSTOMER_MODEL,
	MATERIAL_DESP,
	UNIT,
	VENDOR_CODE,
	VENDOR_NAME,
	DELIVERY_CODE,
	DELIVERY_NAME,
	DATE_FORMAT(
		DELIVERY_DATE,
		'%Y-%m-%d %H:%i:%s'
	) DELIVERY_DATE,
	CREATE_BY,
	DATE_FORMAT(
		CREATE_DATE,
		'%Y-%m-%d %H:%i:%s'
	) CREATE_DATE,
	MODIFY_BY,
	DATE_FORMAT(
		MODIFY_DATE,
		'%Y-%m-%d %H:%i:%s'
	) MODIFY_DATE,
	FLAG,
	VERSION,
	REQUIRE_QTY,
	ORDER_CLOSE,
	PRESACN_FLAG,
	CHECK_FLAG,
	FINISH_QTY,
	DATE_FORMAT(
		CHECK_DATE,
		'%Y-%m-%d %H:%i:%s'
	) CHECK_DATE,
	CHECK_BY,
	FINISH_FLAG
FROM
	ods_wms_order
WHERE
	MODIFY_DATE > DATE_ADD(NOW(), INTERVAL - 30 DAY)
AND PLANT IN (
	SELECT DISTINCT
		cd.`CODE`
	FROM
		cd_factory cd
	WHERE
		cd.country_code = '6600'
)