SELECT
	ROW_ID,
	PLAN_NO,
	ITEM_NO,
	TYPE,
	DATE_FORMAT(
		PLAN_DATE,
		'%Y-%m-%d %H:%i:%s'
	) PLAN_DATE,
	PRODUCT_NAME,
	PRODUCT_CODE,
	PRODUCT_MODEL,
	CUSTOMER_MODEL,
	MATERIAL_NO,
	MATERIAL_DESP,
	DELIVER_CITY_NAME,
	GI_LOCATION,
	RECEIPT_CITY_NAME,
	GR_LOCATION,
	PLAN_QTY,
	FACTORY_QTY,
	ACTUAL_ATY,
	UNIT,
	ORDER_STATUS,
	FACTORY_CONFIRM,
	LOGISTICS_CONFIRM,
	PLAN_VEHICLE_QTY,
	ACTUAL_VEHICLE_QTY,
	CREATE_BY,
	DATE_FORMAT(
		CREATE_DATE,
		'%Y-%m-%d %H:%i:%s'
	) CREATE_DATE,
	MODIFY_BY,
	DATE_FORMAT(
		MODIFY_DATE,
		'%Y-%m-%d %H:%i:%s'
	) MODIFY_DATE,
	FLAG,
	VERSION,
	FACTORY_REMARK,
	LOGISTICS_REMARK,
	REMARK,
	DELIVER_CITY_CODE,
	RECEIPT_CITY_CODE,
	GR_LOCATION_CODE,
	GI_LOCATION_CODE,
	LOGISTICS_QTY,
	APPEND_FLAG,
	APPEND_BY,
	DATE_FORMAT(
		APPEND_DATE,
		'%Y-%m-%d %H:%i:%s'
	) APPEND_DATE
FROM
	ods_plan_info
WHERE
	MODIFY_DATE > DATE_ADD(NOW(), INTERVAL - 30 DAY)
AND (
	DELIVER_CITY_CODE IN (
		SELECT DISTINCT
			cd.`CODE`
		FROM
			cd_factory cd
		WHERE
			cd.country_code = '6600'
	)
	OR RECEIPT_CITY_CODE IN (
		SELECT DISTINCT
			cd2.`CODE`
		FROM
			cd_factory cd2
		WHERE
			cd2.country_code = '6600'
	)
)