SELECT
  id
, NAME
, DESCRIPTION
, URL
, TYPE
, STATUS
, CODE
, CONFIGURATION
, MODULE_NAME
, DATE_FORMAT(
		GMT_CREATE,
		'%Y-%m-%d %H:%i:%s'
	) GMT_CREATE
, DATE_FORMAT(
		GMT_MODIFIED,
		'%Y-%m-%d %H:%i:%s'
	) GMT_MODIFIED
, CREATE_BY
, LAST_MODIFIED_BY
, ORDER_INDEX
, PARENT_ID
, ICON_URL
, WIDTH
, HEIGHT
, FILE_ID
, COUNTRY_CODE
FROM resource_info
WHERE
	GMT_MODIFIED > DATE_ADD(NOW(), INTERVAL - 30 DAY)
AND COUNTRY_CODE = '6600'