SELECT
  id
, NAME
, DESCRIPTION
, DATE_FORMAT(
		GMT_CREATE,
		'%Y-%m-%d %H:%i:%s'
	) GMT_CREATE
, DATE_FORMAT(
		GMT_MODIFIED,
		'%Y-%m-%d %H:%i:%s'
	) GMT_MODIFIED
, CREATE_BY
, LAST_MODIFIED_BY
, COUNTRY_CODE
FROM role
WHERE
	GMT_MODIFIED > DATE_ADD(NOW(), INTERVAL - 30 DAY)
AND COUNTRY_CODE = '6600'