SELECT
  ROW_ID
, DN_NO
, DN_ITEM_NO
, SELL_NO
, SELL_ORDER_TYPE
, PLANT
, DN_DOC_DATE
, DN_LAST_MODIFY_DATE
, DN_CREATE_BY
, MATERIAL_NO
, CUSTOMER_MODEL
, MATERIAL_DESP
, QTY
, LOCATION
, CUSTOMER_NO
, CUSTOMER_NAME
, DELIVERY_CODE
, DELIVERY_NAME
, DELIVERY_DATE
, DATE_FORMAT(
		CREATE_DATE,
		'%Y-%m-%d %H:%i:%s'
	) CREATE_DATE
, DATE_FORMAT(
		MODIFY_DATE,
		'%Y-%m-%d %H:%i:%s'
	) MODIFY_DATE
, VERSION
, DN_CLOSE
, FINISH_QTY
, UNIT
, DELIVER_DATE
, BILLING
, BILLING_ITEM
, FINISH_FLAG
, FLAG
, CREATE_BY
, MODIFY_BY
, REGION
, CITY
, COST_FLAG
, COST_MSG
, SAP_FLAG
, SAP_MSG
, SAP_DOC_NO
, SAP_SEND_ID
, POSTING_DATE
FROM stg_dn_down
where plant in (select fac.code from cd_factory fac where fac.country_code='6600')
and MODIFY_DATE >DATE_ADD(NOW(),INTERVAL -30 DAY)
