SELECT
  id
, NAME
, PASSWORD
, STATUS
, EMAIL
, TYPE
, NICK_NAME
, LAST_LOGIN_IP
, CURRENT_LOGIN_IP
, DATE_FORMAT(
		LAST_LOGIN_TIME,
		'%Y-%m-%d %H:%i:%s'
	) LAST_LOGIN_TIME
, LOGIN_ATTEMPT_TIMES
, DATE_FORMAT(
		LOGIN_FAILD_TIME,
		'%Y-%m-%d %H:%i:%s'
	) LOGIN_FAILD_TIME
, PASSWORD_FIRST_MODIFIED_FLAG
, DATE_FORMAT(
		PASSWORD_EXPIRE_TIME,
		'%Y-%m-%d %H:%i:%s'
	) PASSWORD_EXPIRE_TIME
, DATE_FORMAT(
		GMT_CREATE,
		'%Y-%m-%d %H:%i:%s'
	) GMT_CREATE
, DATE_FORMAT(
		GMT_MODIFIED,
		'%Y-%m-%d %H:%i:%s'
	) GMT_MODIFIED
, CREATE_BY
, LAST_MODIFIED_BY
, ENCODE
, DATE_FORMAT(
		EXPIRED_TIME,
		'%Y-%m-%d %H:%i:%s'
	) EXPIRED_TIME
, MEMBER_ID
, RF_SIGN
, DUTY_TYPE
, PRODUCT_DIVISION,
COUNTRY_CODE
FROM user_info
where country_code ='6600'

