package com.haier.hevwms.webinterface.PostSTODNReceiveFromYueNanWMSToGVS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2015-12-16T14:29:25.857+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "TransGoodsReceiveFromINDWMSToGVS", 
                  wsdlLocation = "file:/E:/SAPinterface/11_TransGoodsReceiveFromINDWMSToGVS_v1.0.wsdl",
                  targetNamespace = "http://www.example.org/TransGoodsReceiveFromINDWMSToGVS/") 
public class TransGoodsReceiveFromINDWMSToGVS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/TransGoodsReceiveFromINDWMSToGVS/", "TransGoodsReceiveFromINDWMSToGVS");
    public final static QName TransGoodsReceiveFromINDWMSToGVSSOAP = new QName("http://www.example.org/TransGoodsReceiveFromINDWMSToGVS/", "TransGoodsReceiveFromINDWMSToGVSSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/SAPinterface/11_TransGoodsReceiveFromINDWMSToGVS_v1.0.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransGoodsReceiveFromINDWMSToGVS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/SAPinterface/11_TransGoodsReceiveFromINDWMSToGVS_v1.0.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransGoodsReceiveFromINDWMSToGVS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransGoodsReceiveFromINDWMSToGVS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransGoodsReceiveFromINDWMSToGVS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransGoodsReceiveFromINDWMSToGVS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransGoodsReceiveFromINDWMSToGVS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransGoodsReceiveFromINDWMSToGVS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TransGoodsReceiveFromINDWMSToGVS
     */
    @WebEndpoint(name = "TransGoodsReceiveFromINDWMSToGVSSOAP")
    public TransGoodsReceiveFromINDWMSToGVS getTransGoodsReceiveFromINDWMSToGVSSOAP() {
        return super.getPort(TransGoodsReceiveFromINDWMSToGVSSOAP, TransGoodsReceiveFromINDWMSToGVS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransGoodsReceiveFromINDWMSToGVS
     */
    @WebEndpoint(name = "TransGoodsReceiveFromINDWMSToGVSSOAP")
    public TransGoodsReceiveFromINDWMSToGVS getTransGoodsReceiveFromINDWMSToGVSSOAP(WebServiceFeature... features) {
        return super.getPort(TransGoodsReceiveFromINDWMSToGVSSOAP, TransGoodsReceiveFromINDWMSToGVS.class, features);
    }

}
