package com.haier.hevwms.webinterface.PostDNFromYueNanWmsToGVS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2015-11-27T15:44:57.356+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "TransGoodsIssueFromINDWMSToGVS", 
                  wsdlLocation = "file:/E:/SAPinterface/TransGoodsIssueFromINDWMSToGVS.wsdl",
                  targetNamespace = "http://www.example.org/TransGoodsIssueFromINDWMSToGVS/") 
public class TransGoodsIssueFromINDWMSToGVS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/TransGoodsIssueFromINDWMSToGVS/", "TransGoodsIssueFromINDWMSToGVS");
    public final static QName TransGoodsIssueFromINDWMSToGVSSOAP = new QName("http://www.example.org/TransGoodsIssueFromINDWMSToGVS/", "TransGoodsIssueFromINDWMSToGVSSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/SAPinterface/TransGoodsIssueFromINDWMSToGVS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransGoodsIssueFromINDWMSToGVS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/SAPinterface/TransGoodsIssueFromINDWMSToGVS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransGoodsIssueFromINDWMSToGVS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransGoodsIssueFromINDWMSToGVS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransGoodsIssueFromINDWMSToGVS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransGoodsIssueFromINDWMSToGVS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransGoodsIssueFromINDWMSToGVS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransGoodsIssueFromINDWMSToGVS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TransGoodsIssueFromINDWMSToGVS
     */
    @WebEndpoint(name = "TransGoodsIssueFromINDWMSToGVSSOAP")
    public TransGoodsIssueFromINDWMSToGVS getTransGoodsIssueFromINDWMSToGVSSOAP() {
        return super.getPort(TransGoodsIssueFromINDWMSToGVSSOAP, TransGoodsIssueFromINDWMSToGVS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransGoodsIssueFromINDWMSToGVS
     */
    @WebEndpoint(name = "TransGoodsIssueFromINDWMSToGVSSOAP")
    public TransGoodsIssueFromINDWMSToGVS getTransGoodsIssueFromINDWMSToGVSSOAP(WebServiceFeature... features) {
        return super.getPort(TransGoodsIssueFromINDWMSToGVSSOAP, TransGoodsIssueFromINDWMSToGVS.class, features);
    }

}
