
package com.haier.hevwms.sto.service.tms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WmsWebServiceImplService", targetNamespace = "http://wms.services.webservice.api.tms.haier.com/", wsdlLocation = "https://vntms.haier.net/api/tms/ws/wms?wsdl")
public class WmsWebServiceImplService
    extends Service
{

    private final static URL WMSWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WMSWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName WMSWEBSERVICEIMPLSERVICE_QNAME = new QName("http://wms.services.webservice.api.tms.haier.com/", "WmsWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://vntms.haier.net/api/tms/ws/wms?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WMSWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        WMSWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public WmsWebServiceImplService() {
        super(__getWsdlLocation(), WMSWEBSERVICEIMPLSERVICE_QNAME);
    }

    public WmsWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WMSWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public WmsWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, WMSWEBSERVICEIMPLSERVICE_QNAME);
    }

    public WmsWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WMSWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public WmsWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WmsWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WmsWebService
     */
    @WebEndpoint(name = "WmsWebServiceImplPort")
    public WmsWebService getWmsWebServiceImplPort() {
        return super.getPort(new QName("http://wms.services.webservice.api.tms.haier.com/", "WmsWebServiceImplPort"), WmsWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WmsWebService
     */
    @WebEndpoint(name = "WmsWebServiceImplPort")
    public WmsWebService getWmsWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wms.services.webservice.api.tms.haier.com/", "WmsWebServiceImplPort"), WmsWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WMSWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw WMSWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return WMSWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
