
package com.haier.hevwms.sto.service.tms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WmsWebService", targetNamespace = "http://wms.services.webservice.api.tms.haier.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WmsWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.haier.hevwms.sto.service.tms.StatusResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pushLoadInfo", targetNamespace = "http://wms.services.webservice.api.tms.haier.com/", className = "com.haier.hevwms.sto.service.tms.PushLoadInfo")
    @ResponseWrapper(localName = "pushLoadInfoResponse", targetNamespace = "http://wms.services.webservice.api.tms.haier.com/", className = "com.haier.hevwms.sto.service.tms.PushLoadInfoResponse")
    public StatusResult pushLoadInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        LoadParam arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.haier.hevwms.sto.service.tms.StatusResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "finishDn", targetNamespace = "http://wms.services.webservice.api.tms.haier.com/", className = "com.haier.hevwms.sto.service.tms.FinishDn")
    @ResponseWrapper(localName = "finishDnResponse", targetNamespace = "http://wms.services.webservice.api.tms.haier.com/", className = "com.haier.hevwms.sto.service.tms.FinishDnResponse")
    public StatusResult finishDn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.haier.hevwms.sto.service.tms.DnResult>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDn", targetNamespace = "http://wms.services.webservice.api.tms.haier.com/", className = "com.haier.hevwms.sto.service.tms.GetDn")
    @ResponseWrapper(localName = "getDnResponse", targetNamespace = "http://wms.services.webservice.api.tms.haier.com/", className = "com.haier.hevwms.sto.service.tms.GetDnResponse")
    public List<DnResult> getDn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
